### ISSUE TITLE
DriveItem does not have the @microsoft.graph.downloadUrl property

### ISSUE THREAD

**Issue by Pavani-Y** [davidmoten/odata-client#156]
Hi David,
I'm trying to get @microsoft.graph.downloadUrl from drive item retrieved as shown below. But the driveItem does not have the downloadurl property. How can i get the download url.
_DriveItem item = graphService
                            .drives(driveId)
                            .items(itemId)
                            .select("@microsoft.graph.downloadUrl")
                            .get();_
Thanks,
Pavani

**Comment by davidmoten** [comment]
I wouldn't be surprised to see that the Microsoft documentation is wrong one this one because to conform to the OData specification the metadata needs to include a `content@odata.mediaReadLink` field. I'm assuming that the download of the item works which means the link must be present in the metadata. You can thus answer the question yourself quite easily by stepping through the java call or enabling debug logging (see https://github.com/davidmoten/odata-client#logging).

**Comment by Pavani-Y** [comment]
Yup! I could fetch the mediaReadLink and download content too, successfully. Thankyou David.

**Comment by davidmoten** [comment]
Great! I'll close.

**Comment by davidmoten** [comment]
FYI https://github.com/microsoftgraph/microsoft-graph-docs/issues/12534

**Comment by Pavani-Y** [comment]
I'm able to download content with @microsoft.graph.downloadUrl too.

**Comment by davidmoten** [comment]
Ah good. So perhaps graph api doesn't honour the select query for metadata. The OData 4.01 spec implies that it doesn't work with metadata: https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31358942
