### ISSUE TITLE
Invalid Java package names

### ISSUE THREAD

**Issue by rmkellogg** [davidmoten/odata-client#39]
[Azure-Boards-Metadata-v3.0.zip](https://github.com/davidmoten/odata-client/files/5111532/Azure-Boards-Metadata-v3.0.zip)

Using latest release the Java classes generated against Azure Boards includes prefix of "default.x" in generated package names in .java files.  I think there is a missing check for reserved words against the package names generated.

Metadata sample file attached.  I manually modified the .java files to work around.  

Very helpful project.

**Comment by davidmoten** [comment]
That's interesting, can you use the organisation level metadata with the /organisation/project baseUrl?

**Comment by davidmoten** [comment]
Re naming, Analytics for DevOps seems to be how Microsoft describes it. https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/quick-ref?view=azure-devops. Based on that the name seems alright (adding devops to the name is perhaps a good idea) and I'm happy to receive feedback from someone that it doesn't work with service X later and then address that.

I think I'll also drop the template suffix from the artifact name because it will work standalone but I'll document in READMEs how to modify the project with custom metadata.

I grabbed your organization level metadata to test with the /org/project url but it appears you've removed the Custom_TFSID field?

**Comment by davidmoten** [comment]
@rmkellogg If you have time to continue discussing, I've moved this discussion to #41. I'll close this issue now as it has been fixed.
