### ISSUE TITLE
Odata library doesn't have function to check whether a contact has photo and different odata method to get contact photo

### ISSUE THREAD

**Issue by nashikanta** [davidmoten/odata-client#86]
Hi David,

I am looking for an API to directly retrieve a contact photo without having to call get metadata "/photo" first and then call "/photo/$value" which internally does in the below graph library.

**graphService.users(mailid).contacts(contactid).photo().get().getStream().get().get()**

I can achieve with CustomRequest call, but I am looking some other way without having to form URL.
Can you please help me out on this.
Also, can you please help me out on how to check if a contact has photo. Right now Contact metadata doesnt have property something like "hasPhoto". It would be great to have this property in contact metadata

**Comment by davidmoten** [comment]
You are welcome to make a PR for consideration for this one if you like, or to investigate a bit further. I probably won't get round to this one for a while but happy for you to do some of the legwork.

**Comment by davidmoten** [comment]
Re the `hasPhoto` property, nope it doesn't exist in docs: https://docs.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-1.0, so you are probably out of luck. You could make a feature request to Microsoft.

**Comment by davidmoten** [comment]
I notice from the code for [`RequestHepler.createStream`](https://github.com/davidmoten/odata-client/blob/c7bf7761d628f2345b5a81454ae4976c4781da16/odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java#L357) used in this scenario that the object (photo) is retrieved first to be sure of what link to use to obtain the stream. The object metadata contains properties like `@odata.mediaEditLink`, `@odata.editLink` which are used preferentially to the current path + `$value`. Still possible to add the `getStream()` method higher up the call chain but it will need some explication in the javadoc or a more precise method name to indicate that using that method may be less reliable than calling `getStream` on the retrieved object.

**Comment by nashikanta** [comment]
Right now I am using **graphService._custom().getStream** to retrieve contact photo which is pretty straight forward but this is a CustomRequest call and we need to form URI

**Comment by davidmoten** [comment]
I've released 0.1.48 to Maven Central which allows you to do this:

```java
InputStream in = graphService.users(mailid).contacts(contactid).photo().getStreamCurrentPath().get().get();
```
Try it out please.

The `hasPhoto` issue is really for Microsoft to solve for you. When it appears in the service metadata I can update the library.

**Comment by nashikanta** [comment]
Hi David, I tried out the latest  and it is working fine.
Thanks

**Comment by mbasboll** [comment]
Hello David,

I have been playing around with using your library to generate the code to interface with Dynamics 365 Business Central api.  This is looking very promising so far and I am able to retrieve all of the entity sets.  For example I can retrieve all of the PurchaseInvoice entries for a specific company in Business Central by specifying a baseUrl of:

https://api.businesscentral.dynamics.com/v2.0/<environment id>/Sandbox/api/v2.0/companies(<company id>)/

then calling:  client.purchaseInvoices().toList()

However when I try to get a specific invoice by executing: client.purchaseInvoices("<purchase invoice guid>").get() i run into this error:

com.github.davidmoten.odata.client.ClientException: responseCode=404 from url=https://api.businesscentral.dynamics.com/v2.0/<enviornment id>/Sandbox/api/v2.0/companies(<company id>)/purchaseInvoices/3681423d-eed6-4a6a-a612-fffc5562cb60, expectedResponseCode in [200, 200], message=
{"error":{"code":"BadRequest_NotFound","message":"The request URI is not valid. Since the segment 'purchaseInvoices' refers to a collection, this must be the last segment in the request URI or it must be followed by an function or action that can be bound to it otherwise all intermediate segments must refer to a single resource.  CorrelationId:  4d419359-ae9b-41b4-928b-1781d99acb36."}}

As far as I can tell, the problem seems to be in the url.  The resulting url from the call is:

https://api.businesscentral.dynamics.com/v2.0/<enviornment id>/Sandbox/api/v2.0/companies(<company id>)/purchaseInvoices/3681423d-eed6-4a6a-a612-fffc5562cb60

But the Business Central api is expecting a function call like this:

https://api.businesscentral.dynamics.com/v2.0/<enviornment id>/Sandbox/api/v2.0/companies(<company id>)/purchaseInvoices(3681423d-eed6-4a6a-a612-fffc5562cb60)

Any chance you can point me in the direction of where I might be going wrong?

Many thanks,

Morten

**Comment by davidmoten** [comment]
@mbasboll I'll have a look. Can you move this to a new issue please because this has nothing to do with the issue you placed the question on.

**Comment by mbasboll** [comment]
Many thanks Dave, I have moved it to a new issue:

https://github.com/davidmoten/odata-client/issues/103

Not sure if this is an issue at all or just my implementation and use of bound actions in Dynamics 365.

Morten
